name: Unit Tests API

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy JSON files
        run: |
          cp \
          pending_messages.json \
          topics.json \
          users.json \
          -r app/* \
          -r utils/* \
          secret.env \
          $GITHUB_WORKSPACE

      # run: cp pending_messages.json topics.json users.json $GITHUB_WORKSPACE
      # run: cp -r api/* $GITHUB_WORKSPACE

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p '*_test.py'